-- Civilization Unique Ability

INSERT INTO	Types	(Type,										Kind			)
VALUES				('TRAIT_CIVILIZATION_MEDICINAL_MASTERY',	'KIND_TRAIT'	);

INSERT INTO	Traits	(TraitType,									Name,												Description												)
VALUES				('TRAIT_CIVILIZATION_MEDICINAL_MASTERY',	'LOC_TRAIT_CIVILIZATION_MEDICINAL_MASTERY_NAME',	'LOC_TRAIT_CIVILIZATION_MEDICINAL_MASTERY_DESCRIPTION'	);
	
INSERT INTO	CivilizationTraits	(CivilizationType,	TraitType								)
VALUES							('CIVILIZATION_LI',	'TRAIT_CIVILIZATION_MEDICINAL_MASTERY'	);

INSERT INTO	Modifiers	(ModifierId,											ModifierType,									RunOnce,	Permanent	)
VALUES					('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_FRIENDLY',	'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN',	0,			1			),
						('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_NEUTRAL',	'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN',	0,			1			),
						('MODIFIER_MEDICINAL_MASTERY_CHEMISTRY_BOOST',			'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',	0,			1			);

INSERT INTO	ModifierArguments	(ModifierId,											Name,		Value				)
VALUES							('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_FRIENDLY',	'Amount',	'5'					),
								('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_FRIENDLY',	'Type',		'FRIENDLY'			),
								('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_NEUTRAL',	'Amount',	'5'					),
								('MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_NEUTRAL',	'Type',		'NEUTRAL'			),
								('MODIFIER_MEDICINAL_MASTERY_CHEMISTRY_BOOST',			'TechType',	'TECH_CHEMISTRY'	);

INSERT INTO	TraitModifiers	(TraitType,									ModifierId											)
VALUES						('TRAIT_CIVILIZATION_MEDICINAL_MASTERY',	'MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_FRIENDLY'	),
							('TRAIT_CIVILIZATION_MEDICINAL_MASTERY',	'MODIFIER_MEDICINAL_MASTERY_HEALING_BOOST_NEUTRAL'	),
							('TRAIT_CIVILIZATION_MEDICINAL_MASTERY',	'MODIFIER_MEDICINAL_MASTERY_CHEMISTRY_BOOST'		);
